### ISSUE TITLE
Which revision of HSLuv is implemented?

### ISSUE THREAD

**Issue by hartwork** [hsluv/hsluv-emacs#1]
Hi!

I noticed that all the other HSLuv repositories at https://github.com/hsluv mention the revision of HSLuv that they implement — 3 or 4 — in the description of the repository. I could not find the word "revision" within the hsluv-emacs repository. Which revision of HSLuv does branch `master` implement?

Thanks and best, Sebastian

**Comment by boronine** [comment]
Appears to be revision 4 based on the test folder. I updated the description. Thanks!
